galaxy_info:
  author: Duilio Ruggiero
  description: Role to deploy Apache CloudStack infrastructure
  license: Apache-2.0
  min_ansible_version: "2.14"
  # platforms:
  #   - name: Ubuntu
  #     versions:
  #       - jammy
  galaxy_tags: []
dependencies: []
